-- AlterTable
ALTER TABLE `Expense`
    ADD COLUMN `paidAmount` DECIMAL(65, 30) NOT NULL DEFAULT 0.00,
    MODIFY `status` ENUM('PENDING', 'UNPAID', 'PARTIALLY_PAID', 'PAID') NOT NULL DEFAULT 'UNPAID';
