-- AlterTable
ALTER TABLE `Mess` ADD COLUMN `districtId` VARCHAR(191) NULL,
    ADD COLUMN `tags` ENUM('HOME_STYLE_FOOD', 'MONTHLY_PLANS', 'DAILY_FRESH_MEALS', 'FIXED_MENU', 'HYGIENIC_KITCHEN', 'AFFORDABLE_PRICING', 'VEG_AND_NON_VEG', 'ON_TIME_SERVING', 'QUALITY_INGREDIENTS', 'CONSISTENT_TASTE', 'STUDENT_FRIENDLY', 'FAMILY_MESS', 'FLEXIBLE_BOOKING', 'NO_HIDDEN_CHARGES', 'TRUSTED_MESS') NULL;

-- CreateTable
CREATE TABLE `District` (
    `id` VARCHAR(191) NOT NULL,
    `image` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Enquiry` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NULL,
    `message` TEXT NOT NULL,
    `enquiryType` ENUM('USER', 'MESS_OWNER') NOT NULL DEFAULT 'USER',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Mess` ADD CONSTRAINT `Mess_districtId_fkey` FOREIGN KEY (`districtId`) REFERENCES `District`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
